### ISSUE TITLE
nodebb-plugin-buttons-galore problem (V0.0.5) NodeBB (V0.7.2)

### ISSUE THREAD

**Issue by julian9444** [TedRinehart/nodebb-plugin-buttons-galore#9]
![hello43](https://cloud.githubusercontent.com/assets/13120452/9076716/486c1af2-3b26-11e5-8b2a-10e2796ceff8.jpg)

**Comment by TedRinehart** [comment]
This repo is no longer maintained, and its contents are incompatible with current builds of NodeBB.
